sudo: required
services:
  - docker

before_install:
  - docker build -t f1oop/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true f1oop/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-598444950095"
  acces_key_id: 
    secure: "AKIAYWVQZIJHW6SUQ2HN"
  secret_access_key:
    secure: "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"
