sudo: required
services:
  - docker

before_install:
  - docker build -t f1oop/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true f1oop/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-598444950095"
  bucket_path: "Docker"
  on:
    branch: master
  acces_key_id: $AWS_ACCESS_KEY
  secure_key_id: "$AWS_SECRET_KEY"
  skip_cleanup: true
